spring:
  datasource:
    url: jdbc:h2:mem:springDataJpa
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        # one-indexed-parameters: true
logging.level:
  org.hibernate.SQL: debug